module.exports = { 
  current: 
   { city: 'Louisville, KY',
     current: 46,
     summary: 'Sun and clouds mixed. High 51F. Winds NE at 10 to 15 mph.' },
  days: 
   [ { weekday: 'Wednesday',
       month: 'December',
       day: 20,
       weather: 'PARTLY CLOUDY',
       high: '51',
       low: '32',
       weatherCondition: 'partlycloudy' },
     { weekday: 'Thursday',
       month: 'December',
       day: 21,
       weather: 'CLEAR',
       high: '55',
       low: '51',
       weatherCondition: 'clear' },
     { weekday: 'Friday',
       month: 'December',
       day: 22,
       weather: 'CHANCE OF RAIN',
       high: '57',
       low: '44',
       weatherCondition: 'chancerain' },
     { weekday: 'Saturday',
       month: 'December',
       day: 23,
       weather: 'RAIN',
       high: '47',
       low: '30',
       weatherCondition: 'rain' },
     { weekday: 'Sunday',
       month: 'December',
       day: 24,
       weather: 'OVERCAST',
       high: '37',
       low: '22',
       weatherCondition: 'cloudy' },
     { weekday: 'Monday',
       month: 'December',
       day: 25,
       weather: 'CLEAR',
       high: '35',
       low: '19',
       weatherCondition: 'clear' },
     { weekday: 'Tuesday',
       month: 'December',
       day: 26,
       weather: 'PARTLY CLOUDY',
       high: '32',
       low: '20',
       weatherCondition: 'partlycloudy' },
     { weekday: 'Wednesday',
       month: 'December',
       day: 27,
       weather: 'PARTLY CLOUDY',
       high: '33',
       low: '26',
       weatherCondition: 'partlycloudy' },
     { weekday: 'Thursday',
       month: 'December',
       day: 28,
       weather: 'SNOW SHOWERS',
       high: '35',
       low: '23',
       weatherCondition: 'snow' },
     { weekday: 'Friday',
       month: 'December',
       day: 29,
       weather: 'PARTLY CLOUDY',
       high: '31',
       low: '18',
       weatherCondition: 'partlycloudy' } ],
  hours: 
   [ { hour: '12:00 PM',
       weather: 'Partly Cloudy',
       temp: '47',
       weatherCondition: 'partlycloudy' },
     { hour: '1:00 PM',
       weather: 'Partly Cloudy',
       temp: '49',
       weatherCondition: 'partlycloudy' },
     { hour: '2:00 PM',
       weather: 'Partly Cloudy',
       temp: '49',
       weatherCondition: 'partlycloudy' },
     { hour: '3:00 PM',
       weather: 'Clear',
       temp: '51',
       weatherCondition: 'clear' },
     { hour: '4:00 PM',
       weather: 'Clear',
       temp: '50',
       weatherCondition: 'clear' },
     { hour: '5:00 PM',
       weather: 'Clear',
       temp: '48',
       weatherCondition: 'clear' },
     { hour: '6:00 PM',
       weather: 'Clear',
       temp: '45',
       weatherCondition: 'clear' } ] }