/*eslint-disable*/

export const data = {
  response: {
    version: "0.1",
    termsofService: "http://www.wunderground.com/weather/api/d/terms.html",
    features: {
      conditions: 1,
      hourly: 1,
      forecast10day: 1
    }
  },
  current_observation: {
    image: {
      url: "http://icons.wxug.com/graphics/wu2/logo_130x80.png",
      title: "Weather Underground",
      link: "http://www.wunderground.com"
    },
    display_location: {
      full: "Denver, CO",
      city: "Denver",
      state: "CO",
      state_name: "Colorado",
      country: "US",
      country_iso3166: "US",
      zip: "80201",
      magic: "1",
      wmo: "99999",
      latitude: "39.74000168",
      longitude: "-104.98000336",
      elevation: "1598.1"
    },
    observation_location: {
      full: "Capitol Hill, Denver, Colorado",
      city: "Capitol Hill, Denver",
      state: "Colorado",
      country: "US",
      country_iso3166: "US",
      latitude: "39.734711",
      longitude: "-104.977921",
      elevation: "5331 ft"
    },
    estimated: {},
    station_id: "KCODENVE218",
    observation_time: "Last Updated on January 3, 8:54 AM MST",
    observation_time_rfc822: "Wed, 03 Jan 2018 08:54:09 -0700",
    observation_epoch: "1514994849",
    local_time_rfc822: "Wed, 03 Jan 2018 08:54:23 -0700",
    local_epoch: "1514994863",
    local_tz_short: "MST",
    local_tz_long: "America/Denver",
    local_tz_offset: "-0700",
    weather: "Partly Cloudy",
    temperature_string: "25.7 F (-3.5 C)",
    temp_f: 25.7,
    temp_c: -3.5,
    relative_humidity: "26%",
    wind_string: "Calm",
    wind_dir: "SW",
    wind_degrees: 223,
    wind_mph: 0.0,
    wind_gust_mph: 0,
    wind_kph: 0,
    wind_gust_kph: 0,
    pressure_mb: "1029",
    pressure_in: "30.38",
    pressure_trend: "-",
    dewpoint_string: "-4 F (-20 C)",
    dewpoint_f: -4,
    dewpoint_c: -20,
    heat_index_string: "NA",
    heat_index_f: "NA",
    heat_index_c: "NA",
    windchill_string: "26 F (-3 C)",
    windchill_f: "26",
    windchill_c: "-3",
    feelslike_string: "26 F (-3 C)",
    feelslike_f: "26",
    feelslike_c: "-3",
    visibility_mi: "10.0",
    visibility_km: "16.1",
    solarradiation: "33",
    UV: "1.0",
    precip_1hr_string: "0.00 in ( 0 mm)",
    precip_1hr_in: "0.00",
    precip_1hr_metric: " 0",
    precip_today_string: "0.00 in (0 mm)",
    precip_today_in: "0.00",
    precip_today_metric: "0",
    icon: "partlycloudy",
    icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
    forecast_url: "http://www.wunderground.com/US/CO/Denver.html",
    history_url:
      "http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE218",
    ob_url:
      "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.734711,-104.977921",
    nowcast: ""
  },
  forecast: {
    txt_forecast: {
      date: "7:31 AM MST",
      forecastday: [
        {
          period: 0,
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          title: "Wednesday",
          fcttext:
            "Sunshine to start, then a few afternoon clouds. High 51F. Winds light and variable.",
          fcttext_metric:
            "Sunny to partly cloudy. High 11C. Winds light and variable.",
          pop: "0"
        },
        {
          period: 1,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Wednesday Night",
          fcttext: "Some passing clouds. Low 24F. Winds light and variable.",
          fcttext_metric: "Partly cloudy. Low -4C. Winds light and variable.",
          pop: "0"
        },
        {
          period: 2,
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          title: "Thursday",
          fcttext: "Sunny. High near 50F. Winds ESE at 5 to 10 mph.",
          fcttext_metric: "Sunny. High around 10C. Winds light and variable.",
          pop: "0"
        },
        {
          period: 3,
          icon: "nt_clear",
          icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
          title: "Thursday Night",
          fcttext: "A mostly clear sky. Low 27F. Winds SSW at 5 to 10 mph.",
          fcttext_metric: "Clear. Low -3C. Winds light and variable.",
          pop: "0"
        },
        {
          period: 4,
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          title: "Friday",
          fcttext:
            "Sunny, along with a few afternoon clouds. High near 55F. Winds WSW at 5 to 10 mph.",
          fcttext_metric:
            "Except for a few afternoon clouds, mainly sunny. High 12C. Winds WSW at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 5,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Friday Night",
          fcttext: "A few clouds. Low 29F. Winds SW at 5 to 10 mph.",
          fcttext_metric: "A few clouds. Low -2C. Winds SW at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 6,
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          title: "Saturday",
          fcttext: "Partly cloudy. High 53F. Winds SW at 5 to 10 mph.",
          fcttext_metric:
            "Intervals of clouds and sunshine. High 12C. Winds light and variable.",
          pop: "0"
        },
        {
          period: 7,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Saturday Night",
          fcttext: "Partly cloudy skies. Low 31F. Winds light and variable.",
          fcttext_metric:
            "A few clouds from time to time. Low -1C. Winds light and variable.",
          pop: "10"
        },
        {
          period: 8,
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          title: "Sunday",
          fcttext:
            "Sunshine and clouds mixed. High 46F. Winds NW at 10 to 15 mph.",
          fcttext_metric:
            "Sunshine and clouds mixed. High 7C. Winds NW at 15 to 25 km/h.",
          pop: "0"
        },
        {
          period: 9,
          icon: "nt_clear",
          icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
          title: "Sunday Night",
          fcttext: "Clear. Low 28F. Winds SW at 5 to 10 mph.",
          fcttext_metric: "Clear. Low -2C. Winds SW at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 10,
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          title: "Monday",
          fcttext:
            "Generally sunny despite a few afternoon clouds. High near 55F. Winds E at 5 to 10 mph.",
          fcttext_metric:
            "Sunshine and some clouds. High 13C. Winds E at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 11,
          icon: "nt_mostlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
          title: "Monday Night",
          fcttext:
            "Partly cloudy skies early will become overcast later during the night. Low 32F. Winds SW at 5 to 10 mph.",
          fcttext_metric:
            "Partly cloudy skies early will become overcast later during the night. Low around 0C. Winds SW at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 12,
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          title: "Tuesday",
          fcttext:
            "Cloudy skies early will become partly cloudy later in the day. High around 55F. Winds E at 5 to 10 mph.",
          fcttext_metric:
            "Cloudy early with partial sunshine expected late. High 12C. Winds E at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 13,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Tuesday Night",
          fcttext:
            "A few clouds from time to time. Low 34F. Winds SSW at 5 to 10 mph.",
          fcttext_metric: "Partly cloudy. Low 1C. Winds SSW at 10 to 15 km/h.",
          pop: "0"
        },
        {
          period: 14,
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          title: "Wednesday",
          fcttext:
            "Partly to mostly cloudy. High 58F. Winds NW at 5 to 10 mph.",
          fcttext_metric:
            "Partly to mostly cloudy. High 14C. Winds NW at 10 to 15 km/h.",
          pop: "10"
        },
        {
          period: 15,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Wednesday Night",
          fcttext:
            "A few clouds from time to time. Low 29F. Winds NW at 5 to 10 mph.",
          fcttext_metric: "A few clouds. Low -2C. Winds NW at 10 to 15 km/h.",
          pop: "20"
        },
        {
          period: 16,
          icon: "snow",
          icon_url: "http://icons.wxug.com/i/c/k/snow.gif",
          title: "Thursday",
          fcttext:
            "Variably cloudy with snow showers. High 38F. Winds N at 5 to 10 mph. Chance of snow 50%. Snowfall around one inch.",
          fcttext_metric:
            "Occasional snow showers. High 3C. Winds N at 10 to 15 km/h. Chance of snow 50%. Snow accumulations less than 2cm.",
          pop: "50"
        },
        {
          period: 17,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Thursday Night",
          fcttext: "Partly cloudy. Low 24F. Winds light and variable.",
          fcttext_metric:
            "A few clouds. Low near -5C. Winds light and variable.",
          pop: "10"
        },
        {
          period: 18,
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          title: "Friday",
          fcttext: "Sunshine. High 44F. Winds ENE at 5 to 10 mph.",
          fcttext_metric:
            "Mostly sunny skies. High 7C. Winds ENE at 10 to 15 km/h.",
          pop: "10"
        },
        {
          period: 19,
          icon: "nt_partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
          title: "Friday Night",
          fcttext: "Partly cloudy. Low near 25F. Winds light and variable.",
          fcttext_metric:
            "A few clouds from time to time. Low -4C. Winds light and variable.",
          pop: "20"
        }
      ]
    },
    simpleforecast: {
      forecastday: [
        {
          date: {
            epoch: "1515031200",
            pretty: "7:00 PM MST on January 03, 2018",
            day: 3,
            month: 1,
            year: 2018,
            yday: 2,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Wed",
            weekday: "Wednesday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 1,
          high: {
            fahrenheit: "51",
            celsius: "11"
          },
          low: {
            fahrenheit: "24",
            celsius: "-4"
          },
          conditions: "Clear",
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "NE",
            degrees: 41
          },
          avewind: {
            mph: 5,
            kph: 8,
            dir: "NE",
            degrees: 41
          },
          avehumidity: 22,
          maxhumidity: 36,
          minhumidity: 10
        },
        {
          date: {
            epoch: "1515117600",
            pretty: "7:00 PM MST on January 04, 2018",
            day: 4,
            month: 1,
            year: 2018,
            yday: 3,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Thu",
            weekday: "Thursday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 2,
          high: {
            fahrenheit: "50",
            celsius: "10"
          },
          low: {
            fahrenheit: "27",
            celsius: "-3"
          },
          conditions: "Clear",
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "ESE",
            degrees: 115
          },
          avewind: {
            mph: 6,
            kph: 10,
            dir: "ESE",
            degrees: 115
          },
          avehumidity: 33,
          maxhumidity: 49,
          minhumidity: 16
        },
        {
          date: {
            epoch: "1515204000",
            pretty: "7:00 PM MST on January 05, 2018",
            day: 5,
            month: 1,
            year: 2018,
            yday: 4,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Fri",
            weekday: "Friday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 3,
          high: {
            fahrenheit: "55",
            celsius: "13"
          },
          low: {
            fahrenheit: "29",
            celsius: "-2"
          },
          conditions: "Clear",
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "WSW",
            degrees: 242
          },
          avewind: {
            mph: 6,
            kph: 10,
            dir: "WSW",
            degrees: 242
          },
          avehumidity: 37,
          maxhumidity: 55,
          minhumidity: 19
        },
        {
          date: {
            epoch: "1515290400",
            pretty: "7:00 PM MST on January 06, 2018",
            day: 6,
            month: 1,
            year: 2018,
            yday: 5,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Sat",
            weekday: "Saturday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 4,
          high: {
            fahrenheit: "53",
            celsius: "12"
          },
          low: {
            fahrenheit: "31",
            celsius: "-1"
          },
          conditions: "Partly Cloudy",
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "SW",
            degrees: 228
          },
          avewind: {
            mph: 6,
            kph: 10,
            dir: "SW",
            degrees: 228
          },
          avehumidity: 46,
          maxhumidity: 69,
          minhumidity: 24
        },
        {
          date: {
            epoch: "1515376800",
            pretty: "7:00 PM MST on January 07, 2018",
            day: 7,
            month: 1,
            year: 2018,
            yday: 6,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Sun",
            weekday: "Sunday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 5,
          high: {
            fahrenheit: "46",
            celsius: "8"
          },
          low: {
            fahrenheit: "28",
            celsius: "-2"
          },
          conditions: "Partly Cloudy",
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 15,
            kph: 24,
            dir: "NW",
            degrees: 318
          },
          avewind: {
            mph: 10,
            kph: 16,
            dir: "NW",
            degrees: 318
          },
          avehumidity: 52,
          maxhumidity: 72,
          minhumidity: 29
        },
        {
          date: {
            epoch: "1515463200",
            pretty: "7:00 PM MST on January 08, 2018",
            day: 8,
            month: 1,
            year: 2018,
            yday: 7,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Mon",
            weekday: "Monday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 6,
          high: {
            fahrenheit: "55",
            celsius: "13"
          },
          low: {
            fahrenheit: "32",
            celsius: "0"
          },
          conditions: "Clear",
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "E",
            degrees: 93
          },
          avewind: {
            mph: 7,
            kph: 11,
            dir: "E",
            degrees: 93
          },
          avehumidity: 39,
          maxhumidity: 60,
          minhumidity: 18
        },
        {
          date: {
            epoch: "1515549600",
            pretty: "7:00 PM MST on January 09, 2018",
            day: 9,
            month: 1,
            year: 2018,
            yday: 8,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Tue",
            weekday: "Tuesday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 7,
          high: {
            fahrenheit: "55",
            celsius: "13"
          },
          low: {
            fahrenheit: "34",
            celsius: "1"
          },
          conditions: "Partly Cloudy",
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          skyicon: "",
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "E",
            degrees: 101
          },
          avewind: {
            mph: 7,
            kph: 11,
            dir: "E",
            degrees: 101
          },
          avehumidity: 48,
          maxhumidity: 69,
          minhumidity: 24
        },
        {
          date: {
            epoch: "1515636000",
            pretty: "7:00 PM MST on January 10, 2018",
            day: 10,
            month: 1,
            year: 2018,
            yday: 9,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Wed",
            weekday: "Wednesday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 8,
          high: {
            fahrenheit: "58",
            celsius: "14"
          },
          low: {
            fahrenheit: "29",
            celsius: "-2"
          },
          conditions: "Partly Cloudy",
          icon: "partlycloudy",
          icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          skyicon: "",
          pop: 10,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "NW",
            degrees: 325
          },
          avewind: {
            mph: 8,
            kph: 13,
            dir: "NW",
            degrees: 325
          },
          avehumidity: 52,
          maxhumidity: 72,
          minhumidity: 28
        },
        {
          date: {
            epoch: "1515722400",
            pretty: "7:00 PM MST on January 11, 2018",
            day: 11,
            month: 1,
            year: 2018,
            yday: 10,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Thu",
            weekday: "Thursday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 9,
          high: {
            fahrenheit: "38",
            celsius: "3"
          },
          low: {
            fahrenheit: "24",
            celsius: "-4"
          },
          conditions: "Snow Showers",
          icon: "snow",
          icon_url: "http://icons.wxug.com/i/c/k/snow.gif",
          skyicon: "",
          pop: 50,
          qpf_allday: {
            in: 0.13,
            mm: 3
          },
          qpf_day: {
            in: 0.13,
            mm: 3
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.8,
            cm: 2.0
          },
          snow_day: {
            in: 0.8,
            cm: 2.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "N",
            degrees: 350
          },
          avewind: {
            mph: 7,
            kph: 11,
            dir: "N",
            degrees: 350
          },
          avehumidity: 61,
          maxhumidity: 70,
          minhumidity: 47
        },
        {
          date: {
            epoch: "1515808800",
            pretty: "7:00 PM MST on January 12, 2018",
            day: 12,
            month: 1,
            year: 2018,
            yday: 11,
            hour: 19,
            min: "00",
            sec: 0,
            isdst: "0",
            monthname: "January",
            monthname_short: "Jan",
            weekday_short: "Fri",
            weekday: "Friday",
            ampm: "PM",
            tz_short: "MST",
            tz_long: "America/Denver"
          },
          period: 10,
          high: {
            fahrenheit: "44",
            celsius: "7"
          },
          low: {
            fahrenheit: "25",
            celsius: "-4"
          },
          conditions: "Clear",
          icon: "clear",
          icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
          skyicon: "",
          pop: 10,
          qpf_allday: {
            in: 0.0,
            mm: 0
          },
          qpf_day: {
            in: 0.0,
            mm: 0
          },
          qpf_night: {
            in: 0.0,
            mm: 0
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0
          },
          snow_day: {
            in: 0.0,
            cm: 0.0
          },
          snow_night: {
            in: 0.0,
            cm: 0.0
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: "ENE",
            degrees: 62
          },
          avewind: {
            mph: 7,
            kph: 11,
            dir: "ENE",
            degrees: 62
          },
          avehumidity: 54,
          maxhumidity: 71,
          minhumidity: 34
        }
      ]
    }
  },
  hourly_forecast: [
    {
      FCTTIME: {
        hour: "9",
        hour_padded: "09",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1514995200",
        pretty: "9:00 AM MST on January 03, 2018",
        civil: "9:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "27", metric: "-3" },
      dewpoint: { english: "3", metric: "-16" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "19",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "S", degrees: "189" },
      wx: "Sunny",
      uvi: "0",
      humidity: "36",
      windchill: { english: "20", metric: "-7" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "20", metric: "-7" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.31", metric: "1026" }
    },
    {
      FCTTIME: {
        hour: "10",
        hour_padded: "10",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1514998800",
        pretty: "10:00 AM MST on January 03, 2018",
        civil: "10:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "33", metric: "1" },
      dewpoint: { english: "2", metric: "-17" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "16",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "S", degrees: "179" },
      wx: "Sunny",
      uvi: "1",
      humidity: "27",
      windchill: { english: "28", metric: "-2" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "28", metric: "-2" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.26", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "11",
        hour_padded: "11",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515002400",
        pretty: "11:00 AM MST on January 03, 2018",
        civil: "11:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "39", metric: "4" },
      dewpoint: { english: "0", metric: "-18" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "13",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "SSE", degrees: "159" },
      wx: "Sunny",
      uvi: "2",
      humidity: "18",
      windchill: { english: "35", metric: "2" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "35", metric: "2" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.21", metric: "1023" }
    },
    {
      FCTTIME: {
        hour: "12",
        hour_padded: "12",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515006000",
        pretty: "12:00 PM MST on January 03, 2018",
        civil: "12:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "48", metric: "9" },
      dewpoint: { english: "-3", metric: "-19" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "5",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "ESE", degrees: "123" },
      wx: "Sunny",
      uvi: "2",
      humidity: "12",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "48", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.16", metric: "1021" }
    },
    {
      FCTTIME: {
        hour: "13",
        hour_padded: "13",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515009600",
        pretty: "1:00 PM MST on January 03, 2018",
        civil: "1:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "51", metric: "11" },
      dewpoint: { english: "-5", metric: "-21" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "20",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "ENE", degrees: "62" },
      wx: "Mostly Sunny",
      uvi: "2",
      humidity: "10",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "51", metric: "11" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.1", metric: "1019" }
    },
    {
      FCTTIME: {
        hour: "14",
        hour_padded: "14",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515013200",
        pretty: "2:00 PM MST on January 03, 2018",
        civil: "2:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "50", metric: "10" },
      dewpoint: { english: "-5", metric: "-21" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "24",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "NNE", degrees: "17" },
      wx: "Mostly Sunny",
      uvi: "1",
      humidity: "10",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "50", metric: "10" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.07", metric: "1018" }
    },
    {
      FCTTIME: {
        hour: "15",
        hour_padded: "15",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515016800",
        pretty: "3:00 PM MST on January 03, 2018",
        civil: "3:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "48", metric: "9" },
      dewpoint: { english: "-5", metric: "-21" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
      fctcode: "2",
      sky: "30",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "N", degrees: "357" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "11",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "48", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.06", metric: "1018" }
    },
    {
      FCTTIME: {
        hour: "16",
        hour_padded: "16",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515020400",
        pretty: "4:00 PM MST on January 03, 2018",
        civil: "4:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "46", metric: "8" },
      dewpoint: { english: "-2", metric: "-19" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/partlycloudy.gif",
      fctcode: "2",
      sky: "42",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "N", degrees: "359" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "13",
      windchill: { english: "44", metric: "7" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "44", metric: "7" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.07", metric: "1018" }
    },
    {
      FCTTIME: {
        hour: "17",
        hour_padded: "17",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515024000",
        pretty: "5:00 PM MST on January 03, 2018",
        civil: "5:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "42", metric: "6" },
      dewpoint: { english: "-1", metric: "-18" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "48",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "N", degrees: "351" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "16",
      windchill: { english: "39", metric: "4" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "39", metric: "4" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.1", metric: "1019" }
    },
    {
      FCTTIME: {
        hour: "18",
        hour_padded: "18",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515027600",
        pretty: "6:00 PM MST on January 03, 2018",
        civil: "6:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "36", metric: "2" },
      dewpoint: { english: "4", metric: "-16" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "52",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "N", degrees: "357" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "26",
      windchill: { english: "31", metric: "-0" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "31", metric: "-0" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.13", metric: "1020" }
    },
    {
      FCTTIME: {
        hour: "19",
        hour_padded: "19",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515031200",
        pretty: "7:00 PM MST on January 03, 2018",
        civil: "7:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "34", metric: "1" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "56",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "N", degrees: "351" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "32",
      windchill: { english: "30", metric: "-1" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "30", metric: "-1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.15", metric: "1021" }
    },
    {
      FCTTIME: {
        hour: "20",
        hour_padded: "20",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515034800",
        pretty: "8:00 PM MST on January 03, 2018",
        civil: "8:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "34", metric: "1" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "59",
      wspd: { english: "3", metric: "5" },
      wdir: { dir: "NW", degrees: "311" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "32",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "34", metric: "1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "1",
      mslp: { english: "30.17", metric: "1022" }
    },
    {
      FCTTIME: {
        hour: "21",
        hour_padded: "21",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515038400",
        pretty: "9:00 PM MST on January 03, 2018",
        civil: "9:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "34", metric: "1" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Mostly Cloudy",
      icon: "mostlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
      fctcode: "3",
      sky: "60",
      wspd: { english: "2", metric: "3" },
      wdir: { dir: "NW", degrees: "310" },
      wx: "Mostly Cloudy",
      uvi: "0",
      humidity: "30",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "34", metric: "1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "1",
      mslp: { english: "30.19", metric: "1022" }
    },
    {
      FCTTIME: {
        hour: "22",
        hour_padded: "22",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515042000",
        pretty: "10:00 PM MST on January 03, 2018",
        civil: "10:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "32", metric: "0" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "48",
      wspd: { english: "2", metric: "3" },
      wdir: { dir: "W", degrees: "266" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "34",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "32", metric: "0" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "1",
      mslp: { english: "30.2", metric: "1023" }
    },
    {
      FCTTIME: {
        hour: "23",
        hour_padded: "23",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "3",
        mday_padded: "03",
        yday: "2",
        isdst: "0",
        epoch: "1515045600",
        pretty: "11:00 PM MST on January 03, 2018",
        civil: "11:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Wednesday",
        weekday_name_night: "Wednesday Night",
        weekday_name_abbrev: "Wed",
        weekday_name_unlang: "Wednesday",
        weekday_name_night_unlang: "Wednesday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "32", metric: "0" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "50",
      wspd: { english: "2", metric: "3" },
      wdir: { dir: "WNW", degrees: "282" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "33",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "32", metric: "0" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "1",
      mslp: { english: "30.22", metric: "1023" }
    },
    {
      FCTTIME: {
        hour: "0",
        hour_padded: "00",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515049200",
        pretty: "12:00 AM MST on January 04, 2018",
        civil: "12:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "31", metric: "-1" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "43",
      wspd: { english: "3", metric: "5" },
      wdir: { dir: "WSW", degrees: "258" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "36",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "31", metric: "-1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "1",
      mslp: { english: "30.24", metric: "1024" }
    },
    {
      FCTTIME: {
        hour: "1",
        hour_padded: "01",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515052800",
        pretty: "1:00 AM MST on January 04, 2018",
        civil: "1:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "29", metric: "-2" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Partly Cloudy",
      icon: "partlycloudy",
      icon_url: "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
      fctcode: "2",
      sky: "30",
      wspd: { english: "3", metric: "5" },
      wdir: { dir: "W", degrees: "278" },
      wx: "Partly Cloudy",
      uvi: "0",
      humidity: "39",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "29", metric: "-2" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.26", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "2",
        hour_padded: "02",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515056400",
        pretty: "2:00 AM MST on January 04, 2018",
        civil: "2:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "27", metric: "-3" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "21",
      wspd: { english: "3", metric: "5" },
      wdir: { dir: "WSW", degrees: "238" },
      wx: "Mostly Clear",
      uvi: "0",
      humidity: "41",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "27", metric: "-3" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.27", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "3",
        hour_padded: "03",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515060000",
        pretty: "3:00 AM MST on January 04, 2018",
        civil: "3:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "26", metric: "-3" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "12",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SW", degrees: "220" },
      wx: "Clear",
      uvi: "0",
      humidity: "42",
      windchill: { english: "22", metric: "-6" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "22", metric: "-6" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.27", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "4",
        hour_padded: "04",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515063600",
        pretty: "4:00 AM MST on January 04, 2018",
        civil: "4:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "25", metric: "-4" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "5",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SSW", degrees: "204" },
      wx: "Clear",
      uvi: "0",
      humidity: "43",
      windchill: { english: "20", metric: "-7" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "20", metric: "-7" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.27", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "5",
        hour_padded: "05",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515067200",
        pretty: "5:00 AM MST on January 04, 2018",
        civil: "5:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "25", metric: "-4" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "2",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SSW", degrees: "204" },
      wx: "Clear",
      uvi: "0",
      humidity: "42",
      windchill: { english: "20", metric: "-7" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "20", metric: "-7" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.27", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "6",
        hour_padded: "06",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515070800",
        pretty: "6:00 AM MST on January 04, 2018",
        civil: "6:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "26", metric: "-3" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "SW", degrees: "215" },
      wx: "Clear",
      uvi: "0",
      humidity: "39",
      windchill: { english: "21", metric: "-6" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "21", metric: "-6" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.28", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "7",
        hour_padded: "07",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515074400",
        pretty: "7:00 AM MST on January 04, 2018",
        civil: "7:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "27", metric: "-3" },
      dewpoint: { english: "4", metric: "-16" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "1",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SSW", degrees: "208" },
      wx: "Clear",
      uvi: "0",
      humidity: "37",
      windchill: { english: "22", metric: "-6" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "22", metric: "-6" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.28", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "8",
        hour_padded: "08",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515078000",
        pretty: "8:00 AM MST on January 04, 2018",
        civil: "8:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "30", metric: "-1" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SW", degrees: "221" },
      wx: "Sunny",
      uvi: "0",
      humidity: "34",
      windchill: { english: "26", metric: "-3" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "26", metric: "-3" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.29", metric: "1026" }
    },
    {
      FCTTIME: {
        hour: "9",
        hour_padded: "09",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515081600",
        pretty: "9:00 AM MST on January 04, 2018",
        civil: "9:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "33", metric: "1" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "S", degrees: "190" },
      wx: "Sunny",
      uvi: "0",
      humidity: "31",
      windchill: { english: "30", metric: "-1" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "30", metric: "-1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.28", metric: "1025" }
    },
    {
      FCTTIME: {
        hour: "10",
        hour_padded: "10",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515085200",
        pretty: "10:00 AM MST on January 04, 2018",
        civil: "10:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "39", metric: "4" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "S", degrees: "170" },
      wx: "Sunny",
      uvi: "1",
      humidity: "25",
      windchill: { english: "36", metric: "2" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "36", metric: "2" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.25", metric: "1024" }
    },
    {
      FCTTIME: {
        hour: "11",
        hour_padded: "11",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515088800",
        pretty: "11:00 AM MST on January 04, 2018",
        civil: "11:00 AM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "AM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "44", metric: "7" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "SE", degrees: "142" },
      wx: "Sunny",
      uvi: "2",
      humidity: "20",
      windchill: { english: "41", metric: "5" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "41", metric: "5" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.22", metric: "1023" }
    },
    {
      FCTTIME: {
        hour: "12",
        hour_padded: "12",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515092400",
        pretty: "12:00 PM MST on January 04, 2018",
        civil: "12:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "47", metric: "8" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "6", metric: "10" },
      wdir: { dir: "SE", degrees: "131" },
      wx: "Sunny",
      uvi: "2",
      humidity: "17",
      windchill: { english: "43", metric: "6" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "43", metric: "6" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.18", metric: "1022" }
    },
    {
      FCTTIME: {
        hour: "13",
        hour_padded: "13",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515096000",
        pretty: "1:00 PM MST on January 04, 2018",
        civil: "1:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "49", metric: "9" },
      dewpoint: { english: "7", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "ESE", degrees: "107" },
      wx: "Sunny",
      uvi: "2",
      humidity: "17",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "49", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.14", metric: "1021" }
    },
    {
      FCTTIME: {
        hour: "14",
        hour_padded: "14",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515099600",
        pretty: "2:00 PM MST on January 04, 2018",
        civil: "2:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "49", metric: "9" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "E", degrees: "84" },
      wx: "Sunny",
      uvi: "1",
      humidity: "16",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "49", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.11", metric: "1020" }
    },
    {
      FCTTIME: {
        hour: "15",
        hour_padded: "15",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515103200",
        pretty: "3:00 PM MST on January 04, 2018",
        civil: "3:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "49", metric: "9" },
      dewpoint: { english: "5", metric: "-15" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "NE", degrees: "42" },
      wx: "Sunny",
      uvi: "0",
      humidity: "16",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "49", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.11", metric: "1020" }
    },
    {
      FCTTIME: {
        hour: "16",
        hour_padded: "16",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515106800",
        pretty: "4:00 PM MST on January 04, 2018",
        civil: "4:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "48", metric: "9" },
      dewpoint: { english: "6", metric: "-14" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "NNE", degrees: "29" },
      wx: "Sunny",
      uvi: "0",
      humidity: "18",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "48", metric: "9" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.12", metric: "1020" }
    },
    {
      FCTTIME: {
        hour: "17",
        hour_padded: "17",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515110400",
        pretty: "5:00 PM MST on January 04, 2018",
        civil: "5:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "43", metric: "6" },
      dewpoint: { english: "9", metric: "-13" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "NNE", degrees: "22" },
      wx: "Clear",
      uvi: "0",
      humidity: "24",
      windchill: { english: "40", metric: "4" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "40", metric: "4" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.15", metric: "1021" }
    },
    {
      FCTTIME: {
        hour: "18",
        hour_padded: "18",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515114000",
        pretty: "6:00 PM MST on January 04, 2018",
        civil: "6:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "38", metric: "3" },
      dewpoint: { english: "11", metric: "-12" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "3", metric: "5" },
      wdir: { dir: "NE", degrees: "50" },
      wx: "Clear",
      uvi: "0",
      humidity: "32",
      windchill: { english: "-9999", metric: "-9999" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "38", metric: "3" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.17", metric: "1022" }
    },
    {
      FCTTIME: {
        hour: "19",
        hour_padded: "19",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515117600",
        pretty: "7:00 PM MST on January 04, 2018",
        civil: "7:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "34", metric: "1" },
      dewpoint: { english: "12", metric: "-11" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "4", metric: "6" },
      wdir: { dir: "SSW", degrees: "203" },
      wx: "Clear",
      uvi: "0",
      humidity: "39",
      windchill: { english: "30", metric: "-1" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "30", metric: "-1" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.18", metric: "1022" }
    },
    {
      FCTTIME: {
        hour: "20",
        hour_padded: "20",
        min: "00",
        min_unpadded: "0",
        sec: "0",
        year: "2018",
        mon: "1",
        mon_padded: "01",
        mon_abbrev: "Jan",
        mday: "4",
        mday_padded: "04",
        yday: "3",
        isdst: "0",
        epoch: "1515121200",
        pretty: "8:00 PM MST on January 04, 2018",
        civil: "8:00 PM",
        month_name: "January",
        month_name_abbrev: "Jan",
        weekday_name: "Thursday",
        weekday_name_night: "Thursday Night",
        weekday_name_abbrev: "Thu",
        weekday_name_unlang: "Thursday",
        weekday_name_night_unlang: "Thursday Night",
        ampm: "PM",
        tz: "",
        age: "",
        UTCDATE: ""
      },
      temp: { english: "31", metric: "-1" },
      dewpoint: { english: "11", metric: "-12" },
      condition: "Clear",
      icon: "clear",
      icon_url: "http://icons.wxug.com/i/c/k/nt_clear.gif",
      fctcode: "1",
      sky: "0",
      wspd: { english: "5", metric: "8" },
      wdir: { dir: "SSW", degrees: "206" },
      wx: "Clear",
      uvi: "0",
      humidity: "43",
      windchill: { english: "25", metric: "-4" },
      heatindex: { english: "-9999", metric: "-9999" },
      feelslike: { english: "25", metric: "-4" },
      qpf: { english: "0.0", metric: "0" },
      snow: { english: "0.0", metric: "0" },
      pop: "0",
      mslp: { english: "30.18", metric: "1022" }
    }
  ]
};
